version: '3'

services:
  app:
    build: .
    container_name: wordle_solver
    volumes:
      - ./:/streamlit
    ports:
      - 8501:8501
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: unless-stopped
