version: '3'

services:
  app:
    build: .
    container_name: wordle_solver
    volumes:
      - ./:/streamlit
      - /home/dan/.streamlit:/root/.streamlit
    ports:
      - "8501:8501"
    restart: unless-stopped
